language: java
sudo: false
install: true
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk8
    env: _JAVA_OPTIONS="-Xmx2048m -Xms512m -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
addons:
  apt:
    packages:
    - oracle-java8-installer
before_script:
- if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
script:
- mvn clean install jacoco:report sonar:sonar
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.organization=ben12-github
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.branch.name=${TRAVIS_BRANCH}
